# Generated by Django 3.2.7 on 2021-11-11 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0018_remove_job_fav_job'),
        ('accounts', '0002_alter_profile_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fav_job',
            field=models.ManyToManyField(to='job.Job'),
        ),
    ]
