# Generated by Django 3.2.7 on 2022-08-05 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0019_job_address'),
        ('accounts', '0006_alter_profile_fav_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='fav_job',
            field=models.ManyToManyField(to='job.Job'),
        ),
    ]
