# Generated by Django 3.2.7 on 2021-10-06 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0010_apply_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='creat_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
