# Generated by Django 3.2.7 on 2021-10-20 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0014_job_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='favorite_job',
            field=models.IntegerField(default=0),
        ),
    ]
