# Generated by Django 3.2.7 on 2021-11-11 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0017_auto_20211108_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='fav_job',
        ),
    ]
